// Lista padrão de 29 advogados carregada ao criar um novo tribunal.
// TODO: substitua pelos nomes reais utilizados no sistema original.
export const DEFAULT_LAWYERS: string[] = [
  "Ana Beatriz Almeida",
  "Bruno Carvalho Ribeiro",
  "Camila Duarte Fernandes",
  "Daniel Esteves Machado",
  "Eduarda Freitas Gonçalves",
  "Fábio Gomes Henriques",
  "Gabriela Horta Ibrahim",
  "Henrique Iglesias Junqueira",
  "Isabela Junqueira Klein",
  "João Kalil Lopes",
  "Karla Lisboa Moreira",
  "Leandro Martins Nogueira",
  "Mariana Nunes Oliveira",
  "Nathan Oliveira Pacheco",
  "Otávio Pacheco Queiroz",
  "Patrícia Queiroz Ramos",
  "Quintino Ramos Silva",
  "Rafael Silva Teixeira",
  "Sabrina Teixeira Uchoa",
  "Thiago Uchoa Vasques",
  "Ursula Vasques Werneck",
  "Vinícius Werneck Xavier",
  "Wesley Xavier Yamada",
  "Xênia Yamada Zampieri",
  "Yasmin Zampieri Alves",
  "Zeca Alves Barbosa",
  "Amanda Barbosa Coelho",
  "Bernardo Coelho Dias",
  "Cecília Dias Espíndola",
];