/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovoCadastroRouteImport } from './routes/novo-cadastro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdvogadosPadraoRouteImport } from './routes/advogados-padrao'
import { Route as IndexRouteImport } from './routes/index'

const NovoCadastroRoute = NovoCadastroRouteImport.update({
  id: '/novo-cadastro',
  path: '/novo-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadosPadraoRoute = AdvogadosPadraoRouteImport.update({
  id: '/advogados-padrao',
  path: '/advogados-padrao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advogados-padrao': typeof AdvogadosPadraoRoute
  '/login': typeof LoginRoute
  '/novo-cadastro': typeof NovoCadastroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advogados-padrao': typeof AdvogadosPadraoRoute
  '/login': typeof LoginRoute
  '/novo-cadastro': typeof NovoCadastroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advogados-padrao': typeof AdvogadosPadraoRoute
  '/login': typeof LoginRoute
  '/novo-cadastro': typeof NovoCadastroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advogados-padrao' | '/login' | '/novo-cadastro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advogados-padrao' | '/login' | '/novo-cadastro'
  id: '__root__' | '/' | '/advogados-padrao' | '/login' | '/novo-cadastro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvogadosPadraoRoute: typeof AdvogadosPadraoRoute
  LoginRoute: typeof LoginRoute
  NovoCadastroRoute: typeof NovoCadastroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/novo-cadastro': {
      id: '/novo-cadastro'
      path: '/novo-cadastro'
      fullPath: '/novo-cadastro'
      preLoaderRoute: typeof NovoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogados-padrao': {
      id: '/advogados-padrao'
      path: '/advogados-padrao'
      fullPath: '/advogados-padrao'
      preLoaderRoute: typeof AdvogadosPadraoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvogadosPadraoRoute: AdvogadosPadraoRoute,
  LoginRoute: LoginRoute,
  NovoCadastroRoute: NovoCadastroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
