/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TribunaisRouteImport } from './routes/tribunais'
import { Route as IndexRouteImport } from './routes/index'

const TribunaisRoute = TribunaisRouteImport.update({
  id: '/tribunais',
  path: '/tribunais',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tribunais': typeof TribunaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tribunais': typeof TribunaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tribunais': typeof TribunaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tribunais'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tribunais'
  id: '__root__' | '/' | '/tribunais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TribunaisRoute: typeof TribunaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tribunais': {
      id: '/tribunais'
      path: '/tribunais'
      fullPath: '/tribunais'
      preLoaderRoute: typeof TribunaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TribunaisRoute: TribunaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
