/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TribunaisRouteImport } from './routes/tribunais'
import { Route as NovoCadastroRouteImport } from './routes/novo-cadastro'
import { Route as AdvogadosPadraoRouteImport } from './routes/advogados-padrao'
import { Route as IndexRouteImport } from './routes/index'

const TribunaisRoute = TribunaisRouteImport.update({
  id: '/tribunais',
  path: '/tribunais',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoCadastroRoute = NovoCadastroRouteImport.update({
  id: '/novo-cadastro',
  path: '/novo-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadosPadraoRoute = AdvogadosPadraoRouteImport.update({
  id: '/advogados-padrao',
  path: '/advogados-padrao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advogados-padrao': typeof AdvogadosPadraoRoute
  '/novo-cadastro': typeof NovoCadastroRoute
  '/tribunais': typeof TribunaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advogados-padrao': typeof AdvogadosPadraoRoute
  '/novo-cadastro': typeof NovoCadastroRoute
  '/tribunais': typeof TribunaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advogados-padrao': typeof AdvogadosPadraoRoute
  '/novo-cadastro': typeof NovoCadastroRoute
  '/tribunais': typeof TribunaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advogados-padrao' | '/novo-cadastro' | '/tribunais'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advogados-padrao' | '/novo-cadastro' | '/tribunais'
  id: '__root__' | '/' | '/advogados-padrao' | '/novo-cadastro' | '/tribunais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvogadosPadraoRoute: typeof AdvogadosPadraoRoute
  NovoCadastroRoute: typeof NovoCadastroRoute
  TribunaisRoute: typeof TribunaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tribunais': {
      id: '/tribunais'
      path: '/tribunais'
      fullPath: '/tribunais'
      preLoaderRoute: typeof TribunaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo-cadastro': {
      id: '/novo-cadastro'
      path: '/novo-cadastro'
      fullPath: '/novo-cadastro'
      preLoaderRoute: typeof NovoCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogados-padrao': {
      id: '/advogados-padrao'
      path: '/advogados-padrao'
      fullPath: '/advogados-padrao'
      preLoaderRoute: typeof AdvogadosPadraoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvogadosPadraoRoute: AdvogadosPadraoRoute,
  NovoCadastroRoute: NovoCadastroRoute,
  TribunaisRoute: TribunaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
